services:
  backend:
    image: release-system
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_SECURITY_USER_NAME: ${SPRING_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_PASSWORD}
      SPRING_SECURITY_USER_ROLES: ${SPRING_ROLES}
      OCI_REGISTRY_URL: ${OCI_URL}
      OCI_REGISTRY_ECR-USERNAME: ${OCI_USERNAME}
      OCI_REGISTRY_ECR-PASSWORD: ${OCI_PASSWORD}
    ports:
      - "8080:8080"
  db:
    container_name: postgres_container
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/main/resources/db/setup.sql:/docker-entrypoint-initdb.d/1.sql
      - ./src/main/resources/db/fill.sql:/docker-entrypoint-initdb.d/2.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
