spring:
  application:
    name: bureau-release-system
  datasource:
    url: jdbc:postgresql://localhost:5432/release-system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
oci:
  registry:
    url: http://localhost:88
    ecr-username: admin
    ecr-password: Harbor12345
    accept-manifest-types:
      - application/vnd.oci.image.index.v1+json
      - application/vnd.oci.image.manifest.v1+json
release:
  system:
    admin:
      username: admin
      password: admin
      authority: admin
feign:
  httpclient:
    enabled: true
    maxConnections: 200
    maxConnectionsPerRoute: 50
    connectionTimeToLive: 10
  client:
    config:
      oci-registry-client:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: basic
        forceDecoding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    health:
      show-details: when_authorized
      roles: admin, metricListener
  info:
    env:
      enabled: true
info:
  application:
    name: release-system
    description: releases management system application
    version: 0.0.1-SNAPSHOT
