oci:
  registry:
    url: http://localhost:88
    name: /library/testrepo
    ecr-username: admin
    ecr-password: Harbor12345
    accept-manifest-types:
      - application/vnd.oci.image.index.v1+json
      - application/vnd.oci.image.manifest.v1+json
feign:
  httpclient:
    enabled: true
    maxConnections: 200
    maxConnectionsPerRoute: 50
  client:
    config:
      oci-registry-client:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: basic
        forceDecoding: true